### PR TITLE
busco and quast added to mq report

### PR DESCRIPTION
**Pull request by AwanAlKoerdi**

### CODE REVIEW

**Comment by chriswyatt1** [comment]
Looks good. 

I realise now that nf-core rnaseq does this slightly differently on the location we mix the output into `ch_multiqc_files`, in that it does it after each call of the process in the main.nf. 

See:
https://github.com/nf-core/rnaseq/blob/00f924cf92a986a842bb352b3c4ae379c773c989/workflows/rnaseq/main.nf#L162C5-L162C117

In a way, I prefer the way you have done it, as it means that all the multiqc part is in one place rather than spread out after each process. But, I guess if we add optional flags for each process, it would be better to add the mix where we use each process, and it keeps everything modular, if its all packaged at the same time.

**Comment by chriswyatt1** [comment]
I would maybe add like :

```
        GENOME_AND_ANNOTATION (
            ch_fasta,
            ch_gff,
        )
        // Add busco and quast plots to multiqc channel
        // Plots are still not saved in multiqc_plots folder
        ch_multiqc_files = ch_multiqc_files.mix(GENOME_AND_ANNOTATION.out.busco_mq)
        ch_multiqc_files = ch_multiqc_files.mix(GENOME_AND_ANNOTATION.out.quast_mq)
    }
```

**Comment by chriswyatt1** [comment]
Then if you want to add onto the genome only mode too, then it should be good to merge 👍

**Comment by FernandoDuarteF** [comment]
Resolved the only conflict there was, I think we can merge this now.

**Pull request merged**
