### PR TITLE
Fixed genome only option not working

### PR DESCRIPTION
**Pull request by FernandoDuarteF**
Fixed ``--genome_only`` option not working.

### CODE REVIEW

**Comment by chriswyatt1** [comment]
Great, ok, lets wait for our first review, and then push it. I will test it now

**Comment by FernandoDuarteF** [comment]
As mentioned in #53:

* Fixed uncompressing on fasta and gff files not working, as done in #72.
* Improved readability by being more explicit about what each item is in mapping functions.
* Fixed sync problems:
  * Changed ``CREATE_PATH`` so it now outputs a single tuple.
  * Combined fasta and gff channels into a single channel and then splitted then into different two channels using ``multiMap`` operator. Same thing for ``NCBIGENOMEDOWNLOAD`` input.

**Comment by FernandoDuarteF** [comment]
Hi @chriswyatt1, looks like meryl and merqury are working fine on the test datasets.

I think this is ready to be merged.

**Review by chriswyatt1 — COMMENTED** [review]
That all looks good, have tested it and works as expected. Questions/Comments:

1. Will the pipeline now work with mixed inputs, e.g. some with just genomes, other with refseq IDs, etc.?

2. Maybe we should add a option on the REAMDE for this already. 
Although the README does require a revamp with all the new modules/subworkflows added.

**Comment by FernandoDuarteF** [comment]
>     1. Will the pipeline now work with mixed inputs, e.g. some with just genomes, other with refseq IDs, etc.?
It works like this:
* If `--genome_only` is set, it will run on `GENOME_ONLY` mode, it will check if there is a genome present and run. Doesn't check for annotation. If you provide it, it will ignore it.
* If no `--genome_only` is set, it will run on `GENOME_AND_ANNOTAION` mode. It will check for RefSeq ID or local fasta and gff. If not present, it will fail.
Note to myself: I need to improve the error messages.
>     2. Maybe we should add a option on the REAMDE for this already.
>        Although the README does require a revamp with all the new modules/subworkflows added.
Yeah, I haven't look at the README. I'll check tomorrow and see what can I add. Probably a lot.

**Comment by FernandoDuarteF** [comment]
I also added `.pre-commit-config.yaml` to the repository which is needed to commit changes in gitpod.

**Pull request merged**
