### PR TITLE
WIP: Busco ideograms

### PR DESCRIPTION
**Pull request by chriswyatt1**
Added a function to use the Ideograms R plot function to add the genome+annotation busco scores per gene onto chromosome scaffolds.

Need to add for genome only mode

### CODE REVIEW

**Comment by FernandoDuarteF** [comment]
The attribute column (9th) is not consistent between gff files. For this reason BUSCO Ideogram fails when using ``samplesheet.csv`` as input, but woks with the test dataset.

The ``busco_create_table_for_plot.R`` script uses ``inner_join()`` to merge both ``full_table.tsv`` from BUSCO and the gff annotation into a single table, based on the first field of the attibute column of the gff. However, this field is not consistent among datasets.

Will have to modify the script or look for alternatives.

**Comment by FernandoDuarteF** [comment]
This is ready to be merged.

**Comment by FernandoDuarteF** [comment]
It would be good to add a warning that you can't see much on a non chromosome level assembly.

**Comment by chriswyatt1** [comment]
https://github.com/nf-core/genomeqc/issues/90

Also we should try to solve this too, by printing only chromosomes greater than the size of the smallest that has a busco gene on it... I think that would be the best practise. As we only want to see big chromosomes really, or any with a busco gene

**Pull request merged**
